name: Docker Build and Push

on:
  push:
    branches:
      - main
      - feature-terraform
  workflow_dispatch:

jobs:
  call-maven-build:
    uses: ./.github/workflows/maven-build.yml

  docker-build-publish:
    needs: call-maven-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: ./app/target
          
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag java-web-app:${{ github.ref_name }}-${{ github.run_number }}
        working-directory: ./app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ vars.DOCKERHUB_USERNAME }}/java-web-app
          TAG="${{ github.ref_name }}-${{ github.run_number }}"
          docker tag java-web-app:$TAG $IMAGE_NAME:latest
          docker tag java-web-app:$TAG $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG
