name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  call-maven-build:
    uses: ./.github/workflows/maven-build.yml

  docker-build-publish:
    needs: call-maven-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: ./app/target
          
      - name: Get Maven Version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag java-web-app:${{ needs.call-maven-build.outputs.timestamp }}
        working-directory: ./app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag java-web-app:${{ needs.call-maven-build.outputs.timestamp }} ${{ vars.DOCKERHUB_USERNAME }}/java-web-app:latest
          docker push ${{ vars.DOCKERHUB_USERNAME }}/java-web-app:latest
