name: Clean up image tags

on:
  push:
    branches:
      - main
      - feature-terraform
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if needed)
        run: |
          pip install requests  # or any other packages your script uses

      - name: Run Python script
        run: python scripts/cleanup.py
      
      - name: Upload email content
        uses: actions/upload-artifact@v4
        with:
          name: email-content
          path: scripts/content.txt

  
    
  send_email:
    needs: run-python
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download email content
        uses: actions/download-artifact@v4
        with:
          name: email-content


      - name: Read email content from file
        id: readfile
        run: |
          printf "body<<EOF\n%s\nEOF\n" "$(cat scripts/content.txt)" >> "$GITHUB_OUTPUT"

      - name: Send Email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          from: david10mesi@gmail.com
          to: akhil10anil@gmail.com,aaria11official@gmail.com,aariasoman1999@gmail.com
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Dockerhub ${{ github.workflow }} #${{ github.run_id }}'
          body: ${{ steps.readfile.outputs.body }}
