name: Maven Build

on:
  workflow_call:
    outputs:
      timestamp:
        description: "Build timestamp"
        value: ${{ jobs.build.outputs.timestamp }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-ts.outputs.timestamp }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package
        working-directory: ./app

      - name: Set timestamp
        id: set-ts
        run: echo "timestamp=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: app/target/*.jar
