# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
      - f-docker


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      working-directory: ./app
    
    - name: Set timestamp
      id: vars
      run: echo "timestamp=$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag java-web-app:${{ steps.vars.outputs.timestamp }}
      working-directory: ./app

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image
      run: docker tag java-web-app:${{ steps.vars.outputs.timestamp }} ${{ secrets.DOCKER_USERNAME }}/java-web-app:latest && docker push ${{ secrets.DOCKER_USERNAME }}/java-web-app:latest



